import type { Place } from "./types";

/**
 * THE CONTENT FILE.
 *
 * This is where the game is authored. Add a location by appending a `Place`;
 * add a word by appending a `Spot`. The world, the markers, the lesson cards,
 * the quizzes and the progress bar are all generated from this array.
 *
 * Rules of thumb:
 *  - `id`s are save keys. Renaming one resets that spot's progress.
 *  - keep `offset` inside roughly 0.8 * `radius` so props stay on flat ground.
 *  - places should be at least (radiusA + radiusB + 10) apart.
 */
export const PLACES: Place[] = [
  {
    id: "meadow",
    name: "The Meadow",
    nameEs: "La Pradera",
    intro: "You wake up in a warm meadow. Walk around and touch what you see.",
    center: [0, 0],
    radius: 16,
    palette: { ground: "#a8c47a", accent: "#e6dcaa", prop: "#7f9a4e" },
    spots: [
      {
        id: "meadow.sign",
        offset: [4, -5],
        rotation: -0.3,
        prop: "sign",
        vocab: {
          en: "Nice to meet you.",
          es: "Encantado de conocerte.",
          sentence: "Hello! My name is Sam. Nice to meet you.",
          sentenceEs: "¡Hola! Me llamo Sam. Encantado de conocerte.",
          wordClass: "phrase",
          level: "A1",
          emoji: "👋",
        },
      },
      {
        id: "meadow.bench",
        offset: [-6, 3],
        rotation: 0.6,
        prop: "bench",
        vocab: {
          en: "to rest",
          es: "descansar",
          sentence: "I sit on the bench to rest for a while.",
          sentenceEs: "Me siento en el banco para descansar un rato.",
          wordClass: "verb",
          level: "A1",
          emoji: "🪑",
        },
      },
      {
        id: "meadow.tree",
        offset: [8, 6],
        prop: "tree",
        scale: 1.2,
        vocab: {
          en: "the tree",
          es: "el árbol",
          sentence: "The tree gives us shade in the afternoon.",
          sentenceEs: "El árbol nos da sombra por la tarde.",
          wordClass: "noun",
          level: "A1",
          emoji: "🌳",
        },
      },
      {
        id: "meadow.lamp",
        offset: [-3, -9],
        prop: "lamp",
        vocab: {
          en: "the light",
          es: "la luz",
          sentence: "When the sun goes down, the light turns on.",
          sentenceEs: "Cuando el sol se pone, la luz se enciende.",
          wordClass: "noun",
          level: "A1",
          emoji: "💡",
        },
      },
    ],
  },

  {
    id: "harbour",
    name: "The Harbour",
    nameEs: "El Puerto",
    intro: "Salt in the air, ropes and crates. The sea starts here.",
    center: [-44, -36],
    radius: 22,
    palette: { ground: "#d5c69d", accent: "#7fb6c4", prop: "#c46f52" },
    spots: [
      {
        id: "harbour.boat",
        offset: [10, 9],
        rotation: 0.4,
        prop: "boat",
        scale: 1.1,
        vocab: {
          en: "the boat",
          es: "el barco",
          sentence: "The old boat leaves the harbour every morning.",
          sentenceEs: "El viejo barco sale del puerto cada mañana.",
          wordClass: "noun",
          level: "A1",
          emoji: "⛵",
        },
      },
      {
        id: "harbour.crate",
        offset: [-8, 5],
        rotation: 0.9,
        prop: "crate",
        vocab: {
          en: "the crate",
          es: "la caja",
          sentence: "They carry a heavy crate onto the boat.",
          sentenceEs: "Llevan una caja pesada al barco.",
          wordClass: "noun",
          level: "A2",
          emoji: "📦",
        },
      },
      {
        id: "harbour.barrel",
        offset: [-11, -2],
        prop: "barrel",
        vocab: {
          en: "the barrel",
          es: "el barril",
          sentence: "A barrel of fresh water stands by the door.",
          sentenceEs: "Un barril de agua fresca está junto a la puerta.",
          wordClass: "noun",
          level: "A2",
          emoji: "🛢️",
        },
      },
      {
        id: "harbour.flag",
        offset: [2, -12],
        prop: "flag",
        vocab: {
          en: "the flag",
          es: "la bandera",
          sentence: "The flag moves because the wind is strong today.",
          sentenceEs: "La bandera se mueve porque el viento es fuerte hoy.",
          wordClass: "noun",
          level: "A1",
          emoji: "🚩",
        },
      },
      {
        id: "harbour.palm",
        offset: [13, -8],
        prop: "palm",
        scale: 1.15,
        vocab: {
          en: "the palm tree",
          es: "la palmera",
          sentence: "A palm tree grows next to the water.",
          sentenceEs: "Una palmera crece junto al agua.",
          wordClass: "noun",
          level: "A2",
          emoji: "🌴",
        },
      },
      {
        id: "harbour.sign",
        offset: [-2, 12],
        rotation: -0.5,
        prop: "sign",
        vocab: {
          en: "Where does this boat go?",
          es: "¿A dónde va este barco?",
          sentence: "Excuse me, where does this boat go?",
          sentenceEs: "Disculpe, ¿a dónde va este barco?",
          wordClass: "phrase",
          level: "A2",
          emoji: "🧭",
        },
      },
    ],
  },

  {
    id: "market",
    name: "The Market",
    nameEs: "El Mercado",
    intro: "Everyone is talking at once. Perfect place to practise numbers.",
    center: [40, -30],
    radius: 22,
    palette: { ground: "#bcbb8c", accent: "#d98f5a", prop: "#b5543f" },
    spots: [
      {
        id: "market.stall",
        offset: [-9, -6],
        rotation: 0.2,
        prop: "stall",
        vocab: {
          en: "the market stall",
          es: "el puesto del mercado",
          sentence: "The market stall sells fruit and bread.",
          sentenceEs: "El puesto del mercado vende fruta y pan.",
          wordClass: "noun",
          level: "A2",
          emoji: "🏪",
        },
      },
      {
        id: "market.sell",
        offset: [9, -7],
        rotation: -0.4,
        prop: "stall",
        vocab: {
          en: "to sell",
          es: "vender",
          sentence: "She sells vegetables here every Saturday.",
          sentenceEs: "Ella vende verduras aquí todos los sábados.",
          wordClass: "verb",
          level: "A2",
          emoji: "🤝",
        },
      },
      {
        id: "market.bakery",
        offset: [0, -14],
        prop: "house",
        scale: 1.1,
        vocab: {
          en: "the bakery",
          es: "la panadería",
          sentence: "The bread from that bakery is still warm.",
          sentenceEs: "El pan de esa panadería todavía está caliente.",
          wordClass: "noun",
          level: "A2",
          emoji: "🥖",
        },
      },
      {
        id: "market.basket",
        offset: [-4, 4],
        rotation: 1.1,
        prop: "crate",
        scale: 0.85,
        vocab: {
          en: "the basket",
          es: "la cesta",
          sentence: "Put the apples in the basket, please.",
          sentenceEs: "Pon las manzanas en la cesta, por favor.",
          wordClass: "noun",
          level: "A2",
          emoji: "🧺",
        },
      },
      {
        id: "market.well",
        offset: [7, 8],
        prop: "well",
        vocab: {
          en: "the well",
          es: "el pozo",
          sentence: "Long ago, the whole village took water from this well.",
          sentenceEs: "Hace mucho, todo el pueblo sacaba agua de este pozo.",
          wordClass: "noun",
          level: "B1",
          emoji: "🪣",
        },
      },
      {
        id: "market.clock",
        offset: [-11, 9],
        prop: "clock",
        vocab: {
          en: "the clock",
          es: "el reloj",
          sentence: "The clock says it is half past four.",
          sentenceEs: "El reloj dice que son las cuatro y media.",
          wordClass: "noun",
          level: "A1",
          emoji: "🕓",
        },
      },
      {
        id: "market.price",
        offset: [3, 13],
        rotation: -0.2,
        prop: "sign",
        vocab: {
          en: "How much does it cost?",
          es: "¿Cuánto cuesta?",
          sentence: "Excuse me, how much does it cost?",
          sentenceEs: "Disculpe, ¿cuánto cuesta?",
          wordClass: "phrase",
          level: "A1",
          emoji: "💰",
        },
      },
    ],
  },

  {
    id: "forest",
    name: "The Forest Camp",
    nameEs: "El Campamento",
    intro: "Pine needles under your feet. Speak softly here.",
    center: [-36, 40],
    radius: 22,
    palette: { ground: "#7d9a5c", accent: "#5f7a45", prop: "#3f5b34" },
    spots: [
      {
        id: "forest.tent",
        offset: [-6, -7],
        rotation: 0.3,
        prop: "tent",
        scale: 1.1,
        vocab: {
          en: "the tent",
          es: "la tienda de campaña",
          sentence: "We sleep in a small tent under the trees.",
          sentenceEs: "Dormimos en una pequeña tienda de campaña bajo los árboles.",
          wordClass: "noun",
          level: "A2",
          emoji: "⛺",
        },
      },
      {
        id: "forest.campfire",
        offset: [3, -3],
        prop: "campfire",
        vocab: {
          en: "the campfire",
          es: "la fogata",
          sentence: "We sit around the campfire and tell stories.",
          sentenceEs: "Nos sentamos alrededor de la fogata y contamos historias.",
          wordClass: "noun",
          level: "B1",
          emoji: "🔥",
        },
      },
      {
        id: "forest.pine",
        offset: [11, 6],
        prop: "tree",
        scale: 1.4,
        vocab: {
          en: "the pine tree",
          es: "el pino",
          sentence: "That pine tree is older than the whole camp.",
          sentenceEs: "Ese pino es más viejo que todo el campamento.",
          wordClass: "noun",
          level: "A2",
          emoji: "🌲",
        },
      },
      {
        id: "forest.rock",
        offset: [-12, 4],
        rotation: 0.8,
        prop: "rock",
        scale: 1.2,
        vocab: {
          en: "the rock",
          es: "la roca",
          sentence: "Careful — that rock is slippery when it rains.",
          sentenceEs: "Cuidado, esa roca resbala cuando llueve.",
          wordClass: "noun",
          level: "A2",
          emoji: "🪨",
        },
      },
      {
        id: "forest.hike",
        offset: [8, -11],
        rotation: -0.6,
        prop: "sign",
        vocab: {
          en: "to hike",
          es: "hacer senderismo",
          sentence: "Tomorrow we hike to the top of the hill.",
          sentenceEs: "Mañana hacemos senderismo hasta lo alto de la colina.",
          wordClass: "verb",
          level: "B1",
          emoji: "🥾",
        },
      },
      {
        id: "forest.quiet",
        offset: [-3, 12],
        rotation: 0.4,
        prop: "bench",
        vocab: {
          en: "quiet",
          es: "silencioso / tranquilo",
          sentence: "The forest is very quiet in the early morning.",
          sentenceEs: "El bosque está muy tranquilo por la mañana temprano.",
          wordClass: "adjective",
          level: "A2",
          emoji: "🤫",
        },
      },
    ],
  },

  {
    id: "station",
    name: "The Train Station",
    nameEs: "La Estación",
    intro: "Trains leave on time. Your English has to keep up.",
    center: [42, 38],
    radius: 22,
    palette: { ground: "#aeb094", accent: "#8a7f6e", prop: "#7b4f3a" },
    spots: [
      {
        id: "station.timetable",
        offset: [-8, -6],
        prop: "clock",
        scale: 1.1,
        vocab: {
          en: "the timetable",
          es: "el horario",
          sentence: "Check the timetable — the train leaves at ten.",
          sentenceEs: "Mira el horario: el tren sale a las diez.",
          wordClass: "noun",
          level: "B1",
          emoji: "🕐",
        },
      },
      {
        id: "station.wait",
        offset: [6, -8],
        rotation: -0.2,
        prop: "bench",
        vocab: {
          en: "to wait",
          es: "esperar",
          sentence: "We wait on the bench for twenty minutes.",
          sentenceEs: "Esperamos en el banco durante veinte minutos.",
          wordClass: "verb",
          level: "A1",
          emoji: "⏳",
        },
      },
      {
        id: "station.platform",
        offset: [-2, 6],
        rotation: 0.3,
        prop: "sign",
        vocab: {
          en: "the platform",
          es: "el andén",
          sentence: "Your train arrives at platform three.",
          sentenceEs: "Tu tren llega al andén tres.",
          wordClass: "noun",
          level: "A2",
          emoji: "🚉",
        },
      },
      {
        id: "station.office",
        offset: [11, 5],
        rotation: -0.4,
        prop: "house",
        vocab: {
          en: "the ticket office",
          es: "la taquilla",
          sentence: "You can buy a ticket at the ticket office.",
          sentenceEs: "Puedes comprar un billete en la taquilla.",
          wordClass: "noun",
          level: "A2",
          emoji: "🎫",
        },
      },
      {
        id: "station.late",
        offset: [-12, 8],
        prop: "lamp",
        vocab: {
          en: "late",
          es: "tarde / con retraso",
          sentence: "Sorry I am late — the train was delayed.",
          sentenceEs: "Perdón por llegar tarde, el tren se retrasó.",
          wordClass: "adjective",
          level: "A2",
          emoji: "⌛",
        },
      },
      {
        id: "station.nexttrain",
        offset: [4, 13],
        rotation: 0.7,
        prop: "flag",
        vocab: {
          en: "What time is the next train?",
          es: "¿A qué hora sale el próximo tren?",
          sentence: "Excuse me, what time is the next train to the city?",
          sentenceEs: "Disculpe, ¿a qué hora sale el próximo tren a la ciudad?",
          wordClass: "phrase",
          level: "A2",
          emoji: "🚆",
        },
      },
    ],
  },
];

/** Flat index of every spot, with a back-reference to its place. */
export const ALL_SPOTS = PLACES.flatMap((place) =>
  place.spots.map((spot) => ({ place, spot })),
);
